name: erasml_torch

channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
  
dependencies:
  - python=3.11
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - conda-forge::pygrib
  - conda-forge::netCDF4
  - conda-forge::cartopy
  - matplotlib
  - scipy
  - plotly
  - scikit-learn
  - pandas
  - numpy
  - pyproj
  - notebook
  - pip
  - pip:
    - wandb
    - tqdm

